ALTER TABLE business_settings
ADD COLUMN IF NOT EXISTS portfolio_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS highlights_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS about_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS testimonials_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS cta_active BOOLEAN DEFAULT TRUE;
